### ISSUE TITLE
_fetch with context paths

### ISSUE THREAD

**Issue by murtaza52** [ohpauleez/shoreleave#1]
Hi Paul,

Thanks for bringing this library to my attention on the datomic list. 

Paul, I was having a problem with fetch when deploying it as a war archive, and wanted to use a context path other than "/". (https://github.com/ibdknox/fetch/issues/9). Does shoreleave address that issue?

Also are there any examples that I can refer to, I would like to use both the history and the remoting components. 

Again thanks for the great library,

Thanks,
Murtaza

**Comment by ohpauleez** [comment]
Hi Murtaza,
Shoreleave is going to get full documentation real soon, with complete examples.  I'm wrapping up some simple PubSub stuff that will set the stage to do concurrency in CLJS (with embedded webworkers and cross-document PubSub).

I'm still actively developing Shoreleave as I build apps, but it's set to see it's first official release at the next ClojureNYC meetup, June 20th.

I will add the context patch to remotes tomorrow.
Thanks for the request and using the library

**Comment by murtaza52** [comment]
Hi Paul,

Thanks for considering adding the patch. Also if you can release it to clojars it will be great, or as it is in development, should I just use it as a git dependency?

I will be waiting for the release !

Thanks,
Murtaza

**Comment by ohpauleez** [comment]
Currently, I use it as a git dependency, because I actively develop as I use it in other projects.  It should be up on clojars no later than June 20th.  I'm shooting to get a SNAPSHOT on clojars by next weekend.

**Comment by ohpauleez** [comment]
Ok, on the client, you'd do something like this:

```
(defn ^:export ping-api []
  (srm/rpc (api/ping) [pong-response]
    (js/alert pong-response)))

(binding [http_rpc/*remote_uri* "/_ffetch"]
  (ping-api))
```

On the server, there's a new call you need to make, `activate-remotes!`:

```
;; The Barker Web Server                                                                                                                                       
;; --------------------- 
;; Barker serves every view file found in `src/barker/views`                                                                                                   
(server/load-views "src/barker/views/")

;; Remote Namespaces                                                                                                                                           
;; -----------------                                                                                                                                           
(rpc/activate-remotes! "/_ffetch")
(rpc/remote-ns 'barker.api :as "api")

;; Middleware                                                                                                                                                  
;;-----------                                                                                                                                                  
(server/add-middleware ring.middleware.gzip/wrap-gzip)
(server/add-middleware ring.middleware.file-info/wrap-file-info)
(server/add-middleware ring.middleware.anti-forgery/wrap-anti-forgery)
```

Without any args, `activate-remotes!` will use the default route of `/_fetch`

This is landing in master within the hour
