### ISSUE TITLE
Questions for using it from client

### ISSUE THREAD

**Issue by murtaza52** [ohpauleez/shoreleave#2]
Hi Paul,

Thanks for posting the new readme. 

I am trying to currently use your library, I have added it as a git dependency and have a few questions. 

1) What is the need for the below - 

(rpc/remote-ns 'example.api :as "api")

2) I have multiple functions that I would like to define at my server side. So do I need to include the ns for all those functions as shown above? 

3) How do I call the above from client side ?

Also if you could post some gist that would also be very helpful,

Thanks,
Murtaza

**Comment by ohpauleez** [comment]
Thank you for trying to push through and get things done with Shoreleave.

If you only have a few functions you want to expose, you can expose them as global RPC functions.
On your server side (this assumes you're using noir), in one of your `views` files:

``` clojure
(ns my.server
  (:use [noir.core :only [defpage]]
        [noir.shoreleave.rpc :only  [defremote]]))

(defremote ping []
  (do
    (println "Pinged from the client")
    "PONG - from the server"))
```

In your client code, you'd write something like:

``` clojure

(ns my.client
  (:require-macros [shoreleave.client.remotes.macros :as srm]))

(defn ^:export ping-server []
  (srm/rpc (ping) [pong-response]
    (js/alert pong-response)))
```

There will be an example project soon.  I'm finishing up the last pieces of Shoreleave - Blob system, PubSub enhancements, and Web Workers.  After that it's all documentation, examples, and cleaning up.

**Comment by murtaza52** [comment]
Thanks Paul, I will try that out today. Also is it possible to use the letrem macro that fetch is using, it has a nice syntax?

**Comment by ohpauleez** [comment]
letrem is there.

My remotes are a port of `fetch` with CSRF protection, namespaced api's, optional resource path setting, and built using the core Shoreleave abstractions.

Anything that works in fetch works with my remotes as well.

**Comment by murtaza52** [comment]
So how are letrem and rpc different? Pros and con of using one over the another? I also found letrpc that should give the syntax I am looking for.

**Comment by ohpauleez** [comment]
letrpc is Shoreleave's letrem.  Same function, different name.

**Comment by murtaza52** [comment]
Hi Paul,

I am trying to do rpc from client, and this is the error I receive. I am getting this error in cljs compilation -

``` clojure
java.io.FileNotFoundException: Could not locate shoreleave/client/remotes/macros__init.class or shoreleave/client/remotes/macros.clj on classpath: 
```

I have this in require -

  (:require-macros [shoreleave.client.remotes.macros :as srm])

And I have included this dep in my project.clj -

``` clojure
  [shoreleave "0.2.2-SNAPSHOT"]
  [shoreleave/shoreleave-remote-noir "0.2.2-SNAPSHOT"]
```

Thanks,
Murtaza

**Comment by ohpauleez** [comment]
The _.client._ was dropped in the official releases of shoreleave.  So you'd want to do:

`(:require-macros [shoreleave.remotes.macros :as srm])`

From your other ticket, it looks like you figured this out.
