### ISSUE TITLE
CSRF Protection

### ISSUE THREAD

**Issue by murtaza52** [ohpauleez/shoreleave#4]
How does the CSRF protection work ? 

The middleware site states that we have to add the hidden field to the HTML pages, and that this mechanism will not work for web services. So how does it work when we are only doing ajax calls?

Thanks,
Murtaza

**Comment by ohpauleez** [comment]
CSRF protection uses client-side double-submit.  There is a CSRF cookie that ring-anti-forgery uses.  Shoreleave inspects this cookies, grabs the token, and appends the appropriate fields to POST data for you automatically
The middleware automatically does the double-submit compare for you.

If you have ring-anti-forgery, all of shoreleave automatically uses CSRF protection, there's no way to avoid it.

Take a look at the code here: https://github.com/shoreleave/shoreleave-remote/blob/master/src/shoreleave/remotes/common.cljs#L43

I don't suggest this but...
If you're doing client-side only double-submit generation and submission (known as stateless CSRF protection), you'll have to implement yourself and build on top of Shoreleave.  See this for more details: http://appsandsecurity.blogspot.com/2012/01/stateless-csrf-protection.html

**Comment by murtaza52** [comment]
Thanks for the info Paul.

As I understand the CSRF protection you have built is using server state,
however the article suggests using client side generation of cookie for
added protection. If so, though I am no expert on this, however the
protection you have built seems adequate.

Or are you suggesting that if it is a client side app only, then the
additional protection is required ?

Thanks,
Murtaza

On Thu, Jun 21, 2012 at 5:40 PM, Paul deGrandis <
reply@reply.github.com

**Comment by ohpauleez** [comment]
The ring middleware is already creating the cookie and auto-rotating the token, so you don't need to do that client-side.  The middleware also does all of the auto-validation.  You have the best level of CSRF protection already provided.

Shoreleave implements the necessary pieces to make the protection automatic for all POST requests from your client app to your server.

If you were developing a backend that wasn't Clojure or didn't provide the CSRF token, you'd have to generate it on the client, create the CSRF cookie with the anti-forgery name (Shoreleave provides you with the cookie interfaces to do this), and then validate on the server.  If you're following the suggestions above (using the ring middleware), you don't have to do anything special, it's all automatic.
