### ISSUE TITLE
link for marg docs is broken

### ISSUE THREAD

**Issue by murtaza52** [ohpauleez/shoreleave#5]
Hi,

The following link is broken - http://shoreleave.github.com/shoreleave-pubsub/

Thanks,
Murtaza

**Comment by ohpauleez** [comment]
Try it again, it's working for me.

**Comment by murtaza52** [comment]
http://shoreleave.github.com/browser/

Sorry copied the wrong link. this one is broken. I guess the URL is wrong, it should be shoreleave-browser.

**Comment by ohpauleez** [comment]
The should be http://shoreleave.github.com/shoreleave-browser/
