### ISSUE TITLE
error while remoting

### ISSUE THREAD

**Issue by murtaza52** [ohpauleez/shoreleave#6]
Hi,

This is the error that I see in browser's js console - 

TypeError: Cannot read property 'remotes' of undefined
arguments: Array[2]
get message: function getter() { [native code] }
get stack: function getter() { [native code] }
set message: function setter() { [native code] }
set stack: function setter() { [native code] }
type: "non_object_property_load"
**proto**: Error

Below is my client side code -

``` clojure

(ns pm.client.models
  (:require [pm.client.utils :as utils]
            [shoreleave.remote :as sr])
  (:require-macros [shoreleave.remotes.macros :as srm]))

(defn ^:export show
  []
  (srm/letrpc [proj (get-projects)]
              (utils/log "Existing Projects :" proj)))
```

Below is the server code -

``` clojure

(ns pm.views.api
  (:use [noir.shoreleave.rpc :only [defremote]]))

(def projects (atom [{:hello 7}]))

(defremote get-projects
  []
  @projects)

(defremote add-project
  [proj]
  (swap! projects (partial cons proj)))
```

Below is my server.clj -

``` clojure
(ns pm.server
  (:require [noir.server :as server]
            [noir.shoreleave.rpc :as rpc]
            [ring.middleware.gzip]
            [ring.middleware.file-info]
            [ring.middleware.anti-forgery]))

(server/load-views "src/pm/views/")

;;Remote Namesapces
;;-----------------
(rpc/activate-remotes!)
;(rpc/remote-ns 'pm.models.api :as "api")

;;Middleware
;;----------
(server/add-middleware ring.middleware.gzip/wrap-gzip)
(server/add-middleware ring.middleware.file-info/wrap-file-info)
(server/add-middleware ring.middleware.anti-forgery/wrap-anti-forgery)
;(server/add-middleware remote/wrap-remotes)

(def handler (server/gen-handler {:mode :dev :ns 'pm}))

(defn -main [& m]
  (let [mode (keyword (or (first m) :dev))
        port (Integer. (get (System/getenv) "PORT" "9020"))]
    (server/start port {:mode mode
                        :ns 'pm})))
```

I get the above error when I try calling  - pm.client.models.show() - from the js console.

I will appreciate if you can help me resolve it.

Thanks,
Murtaza

**Comment by murtaza52** [comment]
Paul I have also created a sample project in github - https://github.com/murtaza52/pm - containing the above code.

**Comment by ohpauleez** [comment]
I'm taking a look at this today.  I have it working in another project, so I'm not sure where the error is happening.

**Comment by ohpauleez** [comment]
The macro was stale (it wasn't updated with the namespace change).  It'll be pushed as a snapshot momentarily.  When I validate it can be pulled, I'll close this issue.

Thanks for the bug report!

**Comment by murtaza52** [comment]
Thanks for making it work. I had also raised an issue on the pubsub, I am not sure if you received that. 

Thanks,
Murtaza
